#ifndef _XOPEN_SOURCE
# define _XOPEN_SOURCE 800
#endif

#include <stdlib.h>
#include <syslog.h>

#include "mqtt.h"

const payload_required_t packet_to_payload[MQTT_CP_MAX] = {
    [MQTT_CP_CONNECT]     = MQTT_PAYLOAD_REQUIRED,
    [MQTT_CP_CONNACK]     = MQTT_PAYLOAD_NONE,
    [MQTT_CP_PUBLISH]     = MQTT_PAYLOAD_OPTIONAL,
    [MQTT_CP_PUBACK]      = MQTT_PAYLOAD_NONE,
    [MQTT_CP_PUBREC]      = MQTT_PAYLOAD_NONE,
    [MQTT_CP_PUBREL]      = MQTT_PAYLOAD_NONE,
    [MQTT_CP_PUBCOMP]     = MQTT_PAYLOAD_NONE,
    [MQTT_CP_SUBSCRIBE]   = MQTT_PAYLOAD_REQUIRED,
    [MQTT_CP_SUBACK]      = MQTT_PAYLOAD_REQUIRED,
    [MQTT_CP_UNSUBSCRIBE] = MQTT_PAYLOAD_REQUIRED,
    [MQTT_CP_UNSUBACK]    = MQTT_PAYLOAD_REQUIRED,
    [MQTT_CP_PINGREQ]     = MQTT_PAYLOAD_NONE,
    [MQTT_CP_PINGRESP]    = MQTT_PAYLOAD_NONE,
    [MQTT_CP_DISCONNECT]  = MQTT_PAYLOAD_NONE,
    [MQTT_CP_AUTH]        = MQTT_PAYLOAD_NONE,
};

const uint8_t packet_permitted_flags[MQTT_CP_MAX] = {
    [MQTT_CP_CONNECT]     = ~0x0,
    [MQTT_CP_CONNACK]     = ~0x0,
    [MQTT_CP_PUBLISH]     = ~0xf,
    [MQTT_CP_PUBACK]      = ~0x0,
    [MQTT_CP_PUBREC]      = ~0x0,
    [MQTT_CP_PUBREL]      = ~0x2,
    [MQTT_CP_PUBCOMP]     = ~0x0,
    [MQTT_CP_SUBSCRIBE]   = ~0x2,
    [MQTT_CP_SUBACK]      = ~0x0,
    [MQTT_CP_UNSUBSCRIBE] = ~0x2,
    [MQTT_CP_UNSUBACK]    = ~0x0,
    [MQTT_CP_PINGREQ]     = ~0x0,
    [MQTT_CP_PINGRESP]    = ~0x0,
    [MQTT_CP_DISCONNECT]  = ~0x0,
    [MQTT_CP_AUTH]        = ~0x0,
};

const char *const control_packet_str[MQTT_CP_MAX] = {
    [MQTT_CP_CONNECT]     = "CONNECT",
    [MQTT_CP_CONNACK]     = "CONNACK",
    [MQTT_CP_PUBLISH]     = "PUBLISH",
    [MQTT_CP_PUBACK]      = "PUBACK",
    [MQTT_CP_PUBREC]      = "PUBREC",
    [MQTT_CP_PUBREL]      = "PUBREL",
    [MQTT_CP_PUBCOMP]     = "PUBCOMP",
    [MQTT_CP_SUBSCRIBE]   = "SUBSCRIBE",
    [MQTT_CP_SUBACK]      = "SUBACK",
    [MQTT_CP_UNSUBSCRIBE] = "UNSUBSCRIBE",
    [MQTT_CP_UNSUBACK]    = "UNSUBACK",
    [MQTT_CP_PINGREQ]     = "PINGREQ",
    [MQTT_CP_PINGRESP]    = "PINGRESP",
    [MQTT_CP_DISCONNECT]  = "DISCONNECT",
    [MQTT_CP_AUTH]        = "AUTH",
};

const type_t property_to_type[MQTT_PROPERTY_IDENT_MAX] = {
    [MQTT_PROP_PAYLOAD_FORMAT_INDICATOR]          = MQTT_TYPE_BYTE,
    [MQTT_PROP_MESSAGE_EXPIRY_INTERVAL]           = MQTT_TYPE_4BYTE,
    [MQTT_PROP_CONTENT_TYPE]                      = MQTT_TYPE_UTF8_STRING,
    [MQTT_PROP_RESPONSE_TOPIC]                    = MQTT_TYPE_UTF8_STRING,
    [MQTT_PROP_CORRELATION_DATA]                  = MQTT_TYPE_BINARY,
    [MQTT_PROP_SUBSCRIPTION_IDENTIFIER]           = MQTT_TYPE_VARBYTE,
    [MQTT_PROP_SESSION_EXPIRY_INTERVAL]           = MQTT_TYPE_4BYTE,
    [MQTT_PROP_ASSIGNED_CLIENT_IDENTIFIER]        = MQTT_TYPE_UTF8_STRING,
    [MQTT_PROP_SERVER_KEEP_ALIVE]                 = MQTT_TYPE_2BYTE,
    [MQTT_PROP_AUTHENTICATION_METHOD]             = MQTT_TYPE_UTF8_STRING,
    [MQTT_PROP_AUTHENTICATION_DATA]               = MQTT_TYPE_BINARY,
    [MQTT_PROP_REQUEST_PROBLEM_INFORMATION]       = MQTT_TYPE_BYTE,
    [MQTT_PROP_WILL_DELAY_INTERVAL]               = MQTT_TYPE_4BYTE,
    [MQTT_PROP_REQUEST_RESPONSE_INFORMATION]      = MQTT_TYPE_BYTE,
    [MQTT_PROP_RESPONSE_INFORMATION]              = MQTT_TYPE_UTF8_STRING,
    [MQTT_PROP_SERVER_REFERENCE]                  = MQTT_TYPE_UTF8_STRING,
    [MQTT_PROP_REASON_STRING]                     = MQTT_TYPE_UTF8_STRING,
    [MQTT_PROP_RECEIVE_MAXIMUM]                   = MQTT_TYPE_2BYTE,
    [MQTT_PROP_TOPIC_ALIAS_MAXIMUM]               = MQTT_TYPE_2BYTE,
    [MQTT_PROP_TOPIC_ALIAS]                       = MQTT_TYPE_2BYTE,
    [MQTT_PROP_MAXIMUM_QOS]                       = MQTT_TYPE_BYTE,
    [MQTT_PROP_RETAIN_AVAILABLE]                  = MQTT_TYPE_BYTE,
    [MQTT_PROP_USER_PROPERTY]                     = MQTT_TYPE_UTF8_STRING_PAIR,
    [MQTT_PROP_MAXIMUM_PACKET_SIZE]               = MQTT_TYPE_4BYTE,
    [MQTT_PROP_WILDCARD_SUBSCRIPTION_AVAILABLE]   = MQTT_TYPE_BYTE,
    [MQTT_PROP_SUBSCRIPTION_IDENTIFIER_AVAILABLE] = MQTT_TYPE_BYTE,
    [MQTT_PROP_SHARED_SUBSCRIPTION_AVAILABLE]     = MQTT_TYPE_BYTE,
};

/* 2.2.2.2 Table 2-4 */
const type_t property_per_control[MQTT_PROPERTY_IDENT_MAX][MQTT_CP_MAX] = {
    [MQTT_PROP_PAYLOAD_FORMAT_INDICATOR]          = {[MQTT_CP_PUBLISH]=true},
    [MQTT_PROP_MESSAGE_EXPIRY_INTERVAL]           = {[MQTT_CP_PUBLISH]=true},
    [MQTT_PROP_CONTENT_TYPE]                      = {[MQTT_CP_PUBLISH]=true},
    [MQTT_PROP_RESPONSE_TOPIC]                    = {[MQTT_CP_PUBLISH]=true},
    [MQTT_PROP_CORRELATION_DATA]                  = {[MQTT_CP_PUBLISH]=true},
    [MQTT_PROP_SUBSCRIPTION_IDENTIFIER]           = {[MQTT_CP_PUBLISH]=true,[MQTT_CP_SUBSCRIBE]=true},
    [MQTT_PROP_SESSION_EXPIRY_INTERVAL]           = {[MQTT_CP_CONNECT]=true,[MQTT_CP_CONNACK]=true,[MQTT_CP_DISCONNECT]=true},
    [MQTT_PROP_ASSIGNED_CLIENT_IDENTIFIER]        = {[MQTT_CP_CONNACK]=true},
    [MQTT_PROP_SERVER_KEEP_ALIVE]                 = {[MQTT_CP_CONNACK]=true},
    [MQTT_PROP_AUTHENTICATION_METHOD]             = {[MQTT_CP_CONNECT]=true,[MQTT_CP_CONNACK]=true,[MQTT_CP_AUTH]=true},
    [MQTT_PROP_AUTHENTICATION_DATA]               = {[MQTT_CP_CONNECT]=true,[MQTT_CP_CONNACK]=true,[MQTT_CP_AUTH]=true},
    [MQTT_PROP_REQUEST_PROBLEM_INFORMATION]       = {[MQTT_CP_CONNECT]=true},
    [MQTT_PROP_WILL_DELAY_INTERVAL]               = {},
    [MQTT_PROP_REQUEST_RESPONSE_INFORMATION]      = {[MQTT_CP_CONNECT]=true},
    [MQTT_PROP_RESPONSE_INFORMATION]              = {[MQTT_CP_CONNECT]=true},
    [MQTT_PROP_SERVER_REFERENCE]                  = {[MQTT_CP_CONNACK]=true,[MQTT_CP_DISCONNECT]=true},
    [MQTT_PROP_REASON_STRING]                     = {[MQTT_CP_CONNACK]=true,[MQTT_CP_PUBACK]=true,[MQTT_CP_PUBREC]=true,[MQTT_CP_PUBREL]=true,[MQTT_CP_PUBCOMP]=true,[MQTT_CP_SUBACK]=true,[MQTT_CP_UNSUBACK]=true,[MQTT_CP_DISCONNECT]=true,[MQTT_CP_AUTH]=true},
    [MQTT_PROP_RECEIVE_MAXIMUM]                   = {[MQTT_CP_CONNECT]=true,[MQTT_CP_CONNACK]=true},
    [MQTT_PROP_TOPIC_ALIAS_MAXIMUM]               = {[MQTT_CP_CONNECT]=true,[MQTT_CP_CONNACK]=true},
    [MQTT_PROP_TOPIC_ALIAS]                       = {[MQTT_CP_PUBLISH]=true},
    [MQTT_PROP_MAXIMUM_QOS]                       = {[MQTT_CP_CONNACK]=true},
    [MQTT_PROP_RETAIN_AVAILABLE]                  = {[MQTT_CP_CONNACK]=true},
    [MQTT_PROP_USER_PROPERTY]                     = {[MQTT_CP_CONNECT]=true,[MQTT_CP_CONNACK]=true,[MQTT_CP_PUBLISH]=true,[MQTT_CP_PUBACK]=true,[MQTT_CP_PUBREC]=true,[MQTT_CP_PUBREL]=true,[MQTT_CP_PUBCOMP]=true,[MQTT_CP_SUBSCRIBE]=true,[MQTT_CP_SUBACK]=true,[MQTT_CP_UNSUBSCRIBE]=true,[MQTT_CP_UNSUBACK]=true,[MQTT_CP_DISCONNECT]=true,[MQTT_CP_AUTH]=true},
    [MQTT_PROP_MAXIMUM_PACKET_SIZE]               = {[MQTT_CP_CONNECT]=true,[MQTT_CP_CONNACK]=true},
    [MQTT_PROP_WILDCARD_SUBSCRIPTION_AVAILABLE]   = {[MQTT_CP_CONNACK]=true},
    [MQTT_PROP_SUBSCRIPTION_IDENTIFIER_AVAILABLE] = {[MQTT_CP_CONNACK]=true},
    [MQTT_PROP_SHARED_SUBSCRIPTION_AVAILABLE]     = {[MQTT_CP_CONNACK]=true},
};

const char *const property_str[MQTT_PROPERTY_IDENT_MAX] = {
    [MQTT_PROP_PAYLOAD_FORMAT_INDICATOR]          = "PAYLOAD_FORMAT_INDICATOR",
    [MQTT_PROP_MESSAGE_EXPIRY_INTERVAL]           = "MESSAGE_EXPIRY_INTERVAL",
    [MQTT_PROP_CONTENT_TYPE]                      = "CONTENT_TYPE",
    [MQTT_PROP_RESPONSE_TOPIC]                    = "RESPONSE_TOPIC",
    [MQTT_PROP_CORRELATION_DATA]                  = "CORRELATION_DATA",
    [MQTT_PROP_SUBSCRIPTION_IDENTIFIER]           = "SUBSCRIPTION_IDENTIFIER",
    [MQTT_PROP_SESSION_EXPIRY_INTERVAL]           = "SESSION_EXPIRY_INTERVAL",
    [MQTT_PROP_ASSIGNED_CLIENT_IDENTIFIER]        = "ASSIGNED_CLIENT_IDENTIFIER",
    [MQTT_PROP_SERVER_KEEP_ALIVE]                 = "SERVER_KEEP_ALIVE",
    [MQTT_PROP_AUTHENTICATION_METHOD]             = "AUTHENTICATION_METHOD",
    [MQTT_PROP_AUTHENTICATION_DATA]               = "AUTHENTICATION_DATA",
    [MQTT_PROP_REQUEST_PROBLEM_INFORMATION]       = "REQUEST_PROBLEM_INFORMATION",
    [MQTT_PROP_WILL_DELAY_INTERVAL]               = "WILL_DELAY_INTERVAL",
    [MQTT_PROP_REQUEST_RESPONSE_INFORMATION]      = "REQUEST_RESPONSE_INFORMATION",
    [MQTT_PROP_RESPONSE_INFORMATION]              = "RESPONSE_INFORMATION",
    [MQTT_PROP_SERVER_REFERENCE]                  = "SERVER_REFERENCE",
    [MQTT_PROP_REASON_STRING]                     = "REASON_STRING",
    [MQTT_PROP_RECEIVE_MAXIMUM]                   = "RECEIVE_MAXIMUM",
    [MQTT_PROP_TOPIC_ALIAS_MAXIMUM]               = "TOPIC_ALIAS_MAXIMUM",
    [MQTT_PROP_TOPIC_ALIAS]                       = "TOPIC_ALIAS",
    [MQTT_PROP_MAXIMUM_QOS]                       = "MAXIMUM_QOS",
    [MQTT_PROP_RETAIN_AVAILABLE]                  = "RETAIN_AVAILABLE",
    [MQTT_PROP_USER_PROPERTY]                     = "USER_PROPERTY",
    [MQTT_PROP_MAXIMUM_PACKET_SIZE]               = "MAXIMUM_PACKET_SIZE",
    [MQTT_PROP_WILDCARD_SUBSCRIPTION_AVAILABLE]   = "WILDCARD_SUBSCRIPTION_AVAILABLE",
    [MQTT_PROP_SUBSCRIPTION_IDENTIFIER_AVAILABLE] = "SUBSCRIPTION_IDENTIFIER_AVAILABLE",
    [MQTT_PROP_SHARED_SUBSCRIPTION_AVAILABLE]     = "SHARED_SUBSCRIPTION_AVAILABLE",
};

const char *const client_state_str[CLIENT_STATE_MAX] = {
    [CS_NEW] = "NEW",
    [CS_ACTIVE] = "ACTIVE",
    [CS_CLOSING] = "CLOSING",
    [CS_CLOSED] = "CLOSED",
    [CS_DISCONNECTED] = "DISCONNECTED"
};

const char *const message_state_str[MSG_STATE_MAX] = {
    [MSG_NEW] = "NEW",
    [MSG_PREACTIVE] = "PREACTIVE",
    [MSG_ACTIVE] = "ACTIVE",
    [MSG_DEAD] = "DEAD",
};

const char *const session_state_str[SESSION_STATE_MAX] = {
    [SESSION_NEW] = "NEW",
    [SESSION_ACTIVE] = "ACTIVE",
    [SESSION_DELETE] = "DELETE",
};

const char *const topic_state_str[TOPIC_STATE_MAX] = {
    [TOPIC_NEW]       = "NEW",
    [TOPIC_PREACTIVE] = "PREACTIVE",
    [TOPIC_ACTIVE]    = "ACTIVE",
    [TOPIC_DEAD]      = "DEAD",
};

const char *const message_type_str[MSG_TYPE_MAX] = {
    [MSG_NORMAL] = "NORMAL",
    [MSG_WILL] = "WILL",
};

const char *const read_state_str[READ_STATE_MAX] = {
    [READ_STATE_NEW]         = "NEW",
    [READ_STATE_HEADER]      = "HEADER",
    [READ_STATE_MORE_HEADER] = "MORE_HEADER",
    [READ_STATE_BODY]        = "BODY",
};

const char *const subscription_type_str[SUB_TYPE_MAX] = {
    [SUB_NON_SHARED] = "NON_SHARED",
    [SUB_SHARED]     = "SHARED",
};

const char *const priority_str[] = {
    [LOG_EMERG]   = "EMERG",
    [LOG_ALERT]   = "ALERT",
    [LOG_CRIT]    = "CRIT",
    [LOG_ERR]     = "ERR",
    [LOG_WARNING] = "WARNING",
    [LOG_NOTICE]  = "NOTICE",
    [LOG_INFO]    = "INFO",
    [LOG_DEBUG]   = "DEBUG",
    NULL,
};

const char *const packet_dir_str[PACKET_DIR_MAX] = {
    [PACKET_IN]  = "IN",
    [PACKET_OUT] = "OUT",
};

const char *const reason_codes_str[MQTT_REASON_CODE_MAX] =
{
    [MQTT_SUCCESS] = "SUCCESS/NORMAL_DISCONNECTION/GRANTED_QOS_0",
    [MQTT_GRANTED_QOS_1] = "GRANTED_QOS_1",
    [MQTT_GRANTED_QOS_2] = "GRANTED_QOS_2",
    [MQTT_DISCONNECT_WITH_WILL_MESSAGE] = "DISCONNECT_WITH_WILL_MESSAGE",
    [MQTT_NO_MATCHING_SUBSCRIBERS] = "NO_MATCHING_SUBSCRIBERS",
    [MQTT_NO_SUBSCRIPTION_EXISTED] = "NO_SUBSCRIPTION_EXISTED",
    [MQTT_CONTINUE_AUTHENTICATION] = "CONTINUE_AUTHENTICATION",
    [MQTT_REAUTHENTICATE] = "REAUTHENTICATE",
    [MQTT_UNSPECIFIED_ERROR] = "UNSPECIFIED_ERROR",
    [MQTT_MALFORMED_PACKET] = "MALFORMED_PACKET",
    [MQTT_PROTOCOL_ERROR] = "PROTOCOL_ERROR",
    [MQTT_IMPLEMENTATION_SPECIFIC_ERROR] = "IMPLEMENTATION_SPECIFIC_ERROR",
    [MQTT_UNSUPPORTED_PROTOCOL_VERSION] = "UNSUPPORTED_PROTOCOL_VERSION",
    [MQTT_CLIENT_IDENTIFIER_NOT_VALID] = "CLIENT_IDENTIFIER_NOT_VALID",
    [MQTT_BAD_USER_NAME_OR_PASSWORD] = "BAD_USER_NAME_OR_PASSWORD",
    [MQTT_NOT_AUTHORIZED] = "NOT_AUTHORIZED",
    [MQTT_SERVER_UNAVAILABLE] = "SERVER_UNAVAILABLE",
    [MQTT_SERVER_BUSY] = "SERVER_BUSY",
    [MQTT_BANNED] = "BANNED",
    [MQTT_SERVER_SHUTTING_DOWN] = "SERVER_SHUTTING_DOWN",
    [MQTT_BAD_AUTHENTICATION_METHOD] = "BAD_AUTHENTICATION_METHOD",
    [MQTT_KEEP_ALIVE_TIMEOUT] = "KEEP_ALIVE_TIMEOUT",
    [MQTT_SESSION_TAKEN_OVER] = "SESSION_TAKEN_OVER",
    [MQTT_TOPIC_FILTER_INVALID] = "TOPIC_FILTER_INVALID",
    [MQTT_TOPIC_NAME_INVALID] = "TOPIC_NAME_INVALID",
    [MQTT_PACKET_IDENTIFIER_IN_USE] = "PACKET_IDENTIFIER_IN_USE",
    [MQTT_PACKET_IDENTIFIER_NOT_FOUND] = "PACKET_IDENTIFIER_NOT_FOUND",
    [MQTT_RECEIVE_MAXIMUM_EXCEEDED] = "RECEIVE_MAXIMUM_EXCEEDED",
    [MQTT_TOPIC_ALIAS_INVALID] = "TOPIC_ALIAS_INVALID",
    [MQTT_PACKET_TOO_LARGE] = "PACKET_TOO_LARGE",
    [MQTT_MESSAGE_RATE_TOO_HIGH] = "MESSAGE_RATE_TOO_HIGH",
    [MQTT_QUOTA_EXCEEDED] = "QUOTA_EXCEEDED",
    [MQTT_ADMINISTRATIVE_ACTION] = "ADMINISTRATIVE_ACTION",
    [MQTT_PAYLOAD_FORMAT_INVALID] = "PAYLOAD_FORMAT_INVALID",
    [MQTT_RETAIN_NOT_SUPPORTED] = "RETAIN_NOT_SUPPORTED",
    [MQTT_QOS_NOT_SUPPORTED] = "QOS_NOT_SUPPORTED",
    [MQTT_USE_ANOTHER_SERVER] = "USE_ANOTHER_SERVER",
    [MQTT_SERVER_MOVED] = "SERVER_MOVED",
    [MQTT_SHARED_SUBSCRIPTIONS_NOT_SUPPORTED] = "SHARED_SUBSCRIPTIONS_NOT_SUPPORTED",
    [MQTT_CONNECTION_RATE_EXCEEDED] = "CONNECTION_RATE_EXCEEDED",
    [MQTT_MAXIMUM_CONNECT_TIME] = "MAXIMUM_CONNECT_TIME",
    [MQTT_SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED] = "SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED",
    [MQTT_WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED] = "WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED",
};
