#define _XOPEN_SOURCE 800

#include "raft.h"

const char *const raft_status_str[RAFT_MAX_STATUS] = {
    [RAFT_OK] = "OK",
    [RAFT_TRUE] = "TRUE",
    [RAFT_FALSE] = "FALSE",
    [RAFT_NOT_LEADER] = "NOT_LEADER",
    [RAFT_SESSION_EXPIRED] = "SESSION_EXPIRED",
    [RAFT_TIMEOUT] = "TIMEOUT",
};

const char *const raft_rpc_str[RAFT_MAX_RPC] = {
    [RAFT_HELLO]           = "HELLO",
    [RAFT_APPEND_ENTRIES]  = "APPEND_ENTRIES",
    [RAFT_REQUEST_VOTE]    = "REQUEST_VOTE",
    [RAFT_ADD_SERVER]      = "ADD_SERVER",
    [RAFT_REMOVE_SERVER]   = "REMOVE_SERVER",
    [RAFT_CLIENT_REQUEST]  = "CLIENT_REQUEST",
    [RAFT_REGISTER_CLIENT] = "REGISTER_CLIENT",
    [RAFT_CLIENT_QUERY]    = "CLIENT_QUERY",
    
    [RAFT_APPEND_ENTRIES_REPLY]  = "APPEND_ENTRIES_REPLY",
    [RAFT_REQUEST_VOTE_REPLY]    = "REQUEST_VOTE_REPLY",
    [RAFT_ADD_SERVER_REPLY]      = "ADD_SERVER_REPLY",
    [RAFT_REMOVE_SERVER_REPLY]   = "REMOVE_SERVER_REPLY",
    [RAFT_CLIENT_REQUEST_REPLY]  = "CLIENT_REQUEST_REPLY",
    [RAFT_REGISTER_CLIENT_REPLY] = "REGISTER_CLIENT_REPLY",
    [RAFT_CLIENT_QUERY_REPLY]    = "CLIENT_QUERY_REPLY",
};

const char *const raft_mode_str[RAFT_MAX_STATES] = {
    [RAFT_STATE_NONE] = "NONE",
    [RAFT_STATE_FOLLOWER] = "FOLLOWER",
    [RAFT_STATE_CANDIDATE] = "CANDIDATE",
    [RAFT_STATE_LEADER] = "LEADER",
};

const char *const raft_conn_str[RAFT_MAX_CONN] = {
    [RAFT_PEER] = "PEER",
    [RAFT_CLIENT] = "CLIENT",
    [RAFT_SERVER] = "SERVER",
};

const char *const raft_log_str[RAFT_MAX_LOG] = {
    [RAFT_LOG_REGISTER_TOPIC] = "REGISTER_TOPIC",
};
